on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        required: true
      IMAGE_PATH:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TOKEN:
        required: true

name: Build and push to ECR

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'choreography-based-saga/github-actions-templates'
          path: 'wf-scripts'
          token:  ${{ secrets.TOKEN }}
      - name: List files for debugging
        run: ls -R $GITHUB_WORKSPACE/wf-scripts
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.JAVA_VERSION}}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.IMAGE_PATH}}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          $GITHUB_WORKSPACE/wf-scripts/workflow-scripts/build-and-tag-image.sh
          
