on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        required: true
      IMAGE_PATH:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TOKEN:
        required: true

name: Build and push to ECR